// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Assign.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Assign.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

static const ::std::string __AsyncStatefulDemo__Assign__asgn_name = "asgn";

::Ice::Object* IceInternal::upCast(::AsyncStatefulDemo::Assign* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::AsyncStatefulDemo::Assign* p) { return p; }

void
AsyncStatefulDemo::__read(::IceInternal::BasicStream* __is, ::AsyncStatefulDemo::AssignPrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::AsyncStatefulDemo::Assign;
        v->__copyFrom(proxy);
    }
}

bool
IceProxy::AsyncStatefulDemo::Assign::asgn(::Ice::Int item, ::Ice::Int position, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__AsyncStatefulDemo__Assign__asgn_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::AsyncStatefulDemo::Assign* __del = dynamic_cast< ::IceDelegate::AsyncStatefulDemo::Assign*>(__delBase.get());
            return __del->asgn(item, position, __ctx);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::AsyncStatefulDemo::Assign::begin_asgn(::Ice::Int item, ::Ice::Int position, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__AsyncStatefulDemo__Assign__asgn_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __AsyncStatefulDemo__Assign__asgn_name, __del, __cookie);
    try
    {
        __result->__prepare(__AsyncStatefulDemo__Assign__asgn_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->write(item);
        __os->write(position);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::AsyncStatefulDemo::Assign::end_asgn(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __AsyncStatefulDemo__Assign__asgn_name);
    bool __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__getIs();
    __is->startReadEncaps();
    __is->read(__ret);
    __is->endReadEncaps();
    return __ret;
}

const ::std::string&
IceProxy::AsyncStatefulDemo::Assign::ice_staticId()
{
    return ::AsyncStatefulDemo::Assign::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::AsyncStatefulDemo::Assign::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::AsyncStatefulDemo::Assign);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::AsyncStatefulDemo::Assign::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::AsyncStatefulDemo::Assign);
}

::IceProxy::Ice::Object*
IceProxy::AsyncStatefulDemo::Assign::__newInstance() const
{
    return new Assign;
}

bool
IceDelegateM::AsyncStatefulDemo::Assign::asgn(::Ice::Int item, ::Ice::Int position, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __AsyncStatefulDemo__Assign__asgn_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        __os->write(item);
        __os->write(position);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.is();
        __is->startReadEncaps();
        __is->read(__ret);
        __is->endReadEncaps();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateD::AsyncStatefulDemo::Assign::asgn(::Ice::Int item, ::Ice::Int position, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, ::Ice::Int item, ::Ice::Int position, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_item(item),
            _m_position(position)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::AsyncStatefulDemo::Assign* servant = dynamic_cast< ::AsyncStatefulDemo::Assign*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->asgn(_m_item, _m_position, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        ::Ice::Int _m_item;
        ::Ice::Int _m_position;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __AsyncStatefulDemo__Assign__asgn_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, item, position, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::ObjectPtr
AsyncStatefulDemo::Assign::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __AsyncStatefulDemo__Assign_ids[2] =
{
    "::AsyncStatefulDemo::Assign",
    "::Ice::Object"
};

bool
AsyncStatefulDemo::Assign::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__AsyncStatefulDemo__Assign_ids, __AsyncStatefulDemo__Assign_ids + 2, _s);
}

::std::vector< ::std::string>
AsyncStatefulDemo::Assign::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__AsyncStatefulDemo__Assign_ids[0], &__AsyncStatefulDemo__Assign_ids[2]);
}

const ::std::string&
AsyncStatefulDemo::Assign::ice_id(const ::Ice::Current&) const
{
    return __AsyncStatefulDemo__Assign_ids[0];
}

const ::std::string&
AsyncStatefulDemo::Assign::ice_staticId()
{
    return __AsyncStatefulDemo__Assign_ids[0];
}

::Ice::DispatchStatus
AsyncStatefulDemo::Assign::___asgn(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::Ice::Int item;
    ::Ice::Int position;
    __is->read(item);
    __is->read(position);
    __is->endReadEncaps();
    ::IceInternal::BasicStream* __os = __inS.os();
    bool __ret = asgn(item, position, __current);
    __os->write(__ret);
    return ::Ice::DispatchOK;
}

static ::std::string __AsyncStatefulDemo__Assign_all[] =
{
    "asgn",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

::Ice::DispatchStatus
AsyncStatefulDemo::Assign::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__AsyncStatefulDemo__Assign_all, __AsyncStatefulDemo__Assign_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __AsyncStatefulDemo__Assign_all)
    {
        case 0:
        {
            return ___asgn(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
AsyncStatefulDemo::Assign::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
AsyncStatefulDemo::Assign::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
AsyncStatefulDemo::Assign::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type AsyncStatefulDemo::Assign was not generated with stream support";
    throw ex;
}

void
AsyncStatefulDemo::Assign::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type AsyncStatefulDemo::Assign was not generated with stream support";
    throw ex;
}
#endif

void 
AsyncStatefulDemo::__patch__AssignPtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::AsyncStatefulDemo::AssignPtr* p = static_cast< ::AsyncStatefulDemo::AssignPtr*>(__addr);
    assert(p);
    *p = ::AsyncStatefulDemo::AssignPtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::AsyncStatefulDemo::Assign::ice_staticId(), v->ice_id());
    }
}
